#include "Logger.h"

Q_LOGGING_CATEGORY(L_ACCOUNTS, "Accounts")
Q_LOGGING_CATEGORY(L_NETWORK, "Network")
Q_LOGGING_CATEGORY(L_JAVA, "Java")
Q_LOGGING_CATEGORY(L_PROCESS, "Process")
Q_LOGGING_CATEGORY(L_UI, "UI")
Q_LOGGING_CATEGORY(L_WIDGETS, "Widgets")
Q_LOGGING_CATEGORY(L_UPDATER, "Updater")
Q_LOGGING_CATEGORY(L_CONFIG, "Config")
Q_LOGGING_CATEGORY(L_LAUNCHER, "Launcher")
