name: Cross-Platform Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Configure CMake
      run: cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_INSTALLATION_ROOT }}/scripts/buildsystems/vcpkg.cmake"
    - name: Build
      run: cmake --build build
    - name: Build Installer
      run: |
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" /dBuildDir="build" installer.iss
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WerkLauncher-Windows-Installer
        path: out/installer/*.exe

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Qt6 and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build cmake build-essential libgl1-mesa-dev zlib1g-dev \
          qt6-base-dev qt6-base-private-dev libqt6svg6-dev libqt6networkauth6-dev qt6-image-formats-plugins
    - name: Configure
      run: cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build
    - name: Build AppImage
      env:
        BUILD_DIR: build
      run: |
        chmod +x build_appimage.sh
        ./build_appimage.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WerkLauncher-Linux-AppImage
        path: "*.AppImage"

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: brew install qt@6 ninja cmake
    - name: Configure
      run: cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$(brew --prefix qt@6)"
    - name: Build
      run: cmake --build build
    - name: Package DMG
      run: $(brew --prefix qt@6)/bin/macdeployqt build/WerkLauncher.app -dmg
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WerkLauncher-macOS-DMG
        path: build/WerkLauncher.dmg
